apiVersion: v1
kind: Pod
metadata:
  name: cpu-demo
  namespace: default
spec:
  containers:
  - name: cpu-demo-ctr
    image: vish/stress
    resources:
      limits:
        cpu: "400m"
      requests:
        cpu: "200m"
