apiVersion: v1
kind: Service
metadata:
  name: fulfillorder
  labels:
    app: fulfillorder
spec:
  selector:
    app: fulfillorder
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: fulfillorder
  type: ClusterIP
